services:
  airflow:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    container_name: breweries_airflow
    build:
      context: .
      dockerfile: Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - airflow_db:/home/airflow           # airflow.db persiste
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./data:/data
      - ./gai.conf:/etc/gai.conf:ro        # força IPv4
    environment:
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow:/opt/airflow/src
      AIRFLOW__SMTP__SMTP_HOST: "smtp.gmail.com"
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_PORT: "587"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "seu_email@gmail.com"
      AIRFLOW__SMTP__SMTP_USER: "seu_email@gmail.com"
      AIRFLOW__SMTP__SMTP_PASSWORD: "sua_senha_app" 


volumes:
  airflow_db: {}
